version: '3.3'

services:

  db:
    container_name: db
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=full_cycle
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_USER=full_cycle
      - MYSQL_PASSWORD=12345

    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data:/var/lib/mysql
  api:
    container_name: api
    image: node:16
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - db
    env_file:
      - ./.env
  
  nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "80:80"